export { default as Dashboard } from './Admin/Dashboard';
export { default as Cashier } from './Admin/Cashier';
export { default as Category } from './Admin/Category';
export { default as Product } from './Admin/Product';
export { default as Bundling } from './Admin/Bundling';
export { default as BundlingDetail } from './Admin/Bundling/detail';
export { default as BundlingCreate } from './Admin/Bundling/widgets/Create';
export { default as BundlingEdit } from './Admin/Bundling/widgets/Edit';
export { default as ProductDetail } from './Admin/Product/detail';
export { default as ProductCreate } from './Admin/Product/widgets/Create';
export { default as ProductEdit } from './Admin/Product/widgets/Edit';
export { default as TransactionHistory } from './Admin/TransactionHistory';
export { default as LandingPage } from './Customer/Landing Page';
export { default as Pemesanan } from './Admin/Pemesanan';
export { default as User } from './Admin/User';
export { default as ActivityLogs } from './Admin/Log Activity';